### ISSUE TITLE
Need default value to function?

### ISSUE THREAD

**Issue by Moelf** [MilesCranmer/DeprecateKeywords.jl#6]
It is observed in https://github.com/Moelf/FHist.jl/pull/83 that you need default value for the keyword argument for this package to work, is this intended?

**Comment by MilesCranmer** [comment]
Hm, yes, I didn’t think this would be a potential use case so it’s not set up right now. But I guess it could be integrated by, in the macro, assigning the default value abstract type, and then checking if it has been set or not within the function body.

**Comment by MilesCranmer** [comment]
Fixed by #7. Could you take a look when you get a chance? Thanks!

**Comment by bojohnson5** [comment]
@Moelf Looks like the `no-defaults` branch is working. I'm guessing I'll wait for @MilesCranmer to merge it into `master` and then update my own pull request on [Moelf/FHist.jl#83](https://github.com/Moelf/FHist.jl/pull/83)?
